### ISSUE TITLE
Deasync not in binding file

### ISSUE THREAD

**Issue by klefo0** [c3cbot/c3cbot#2]
Tried to run c3cbot for the first time, I've encounter this error
```
Error: Could not locate the bindings file. Tried:
 → E:\BotChat\Bot_Face\c3cbot\node_modules\deasync\build\deasync.node
 → E:\BotChat\Bot_Face\c3cbot\node_modules\deasync\build\Debug\deasync.node
 → E:\BotChat\Bot_Face\c3cbot\node_modules\deasync\build\Release\deasync.node
 → E:\BotChat\Bot_Face\c3cbot\node_modules\deasync\out\Debug\deasync.node
 → E:\BotChat\Bot_Face\c3cbot\node_modules\deasync\Debug\deasync.node
 → E:\BotChat\Bot_Face\c3cbot\node_modules\deasync\out\Release\deasync.node
 → E:\BotChat\Bot_Face\c3cbot\node_modules\deasync\Release\deasync.node
 → E:\BotChat\Bot_Face\c3cbot\node_modules\deasync\build\default\deasync.node
 → E:\BotChat\Bot_Face\c3cbot\node_modules\deasync\compiled\19.8.1\win32\x64\deasync.node
 → E:\BotChat\Bot_Face\c3cbot\node_modules\deasync\addon-build\release\install-root\deasync.node
 → E:\BotChat\Bot_Face\c3cbot\node_modules\deasync\addon-build\debug\install-root\deasync.node
 → E:\BotChat\Bot_Face\c3cbot\node_modules\deasync\addon-build\default\install-root\deasync.node
 → E:\BotChat\Bot_Face\c3cbot\node_modules\deasync\lib\binding\node-v111-win32-x64\deasync.node
    at bindings (E:\BotChat\Bot_Face\c3cbot\node_modules\bindings\bindings.js:126:9)
    at Object.<anonymous> (E:\BotChat\Bot_Face\c3cbot\node_modules\deasync\index.js:30:31)
    at Module._compile (node:internal/modules/cjs/loader:1275:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1329:10)
    at Module.load (node:internal/modules/cjs/loader:1133:32)
    at Module._load (node:internal/modules/cjs/loader:972:12)
    at Module.require (node:internal/modules/cjs/loader:1157:19)
    at require (node:internal/modules/helpers:119:18)
    at Object.<anonymous> (E:\BotChat\Bot_Face\c3cbot\node_modules\wait-for-stuff\index.js:21:20)
    at Module._compile (node:internal/modules/cjs/loader:1275:14) {
  tries: [
    'E:\\BotChat\\Bot_Face\\c3cbot\\node_modules\\deasync\\build\\deasync.node',
    'E:\\BotChat\\Bot_Face\\c3cbot\\node_modules\\deasync\\build\\Debug\\deasync.node',
    'E:\\BotChat\\Bot_Face\\c3cbot\\node_modules\\deasync\\build\\Release\\deasync.node',
    'E:\\BotChat\\Bot_Face\\c3cbot\\node_modules\\deasync\\out\\Debug\\deasync.node',
    'E:\\BotChat\\Bot_Face\\c3cbot\\node_modules\\deasync\\Debug\\deasync.node',
    'E:\\BotChat\\Bot_Face\\c3cbot\\node_modules\\deasync\\out\\Release\\deasync.node',
    'E:\\BotChat\\Bot_Face\\c3cbot\\node_modules\\deasync\\Release\\deasync.node',
    'E:\\BotChat\\Bot_Face\\c3cbot\\node_modules\\deasync\\build\\default\\deasync.node',
    'E:\\BotChat\\Bot_Face\\c3cbot\\node_modules\\deasync\\compiled\\19.8.1\\win32\\x64\\deasync.node',
    'E:\\BotChat\\Bot_Face\\c3cbot\\node_modules\\deasync\\addon-build\\release\\install-root\\deasync.node',
    'E:\\BotChat\\Bot_Face\\c3cbot\\node_modules\\deasync\\addon-build\\debug\\install-root\\deasync.node',
    'E:\\BotChat\\Bot_Face\\c3cbot\\node_modules\\deasync\\addon-build\\default\\install-root\\deasync.node',
    'E:\\BotChat\\Bot_Face\\c3cbot\\node_modules\\deasync\\lib\\binding\\node-v111-win32-x64\\deasync.node'
  ]
}
```

I have search in c3cbot local repo, but not found any code have used `deasync`. It only appeared in package.json.

**Comment by BadAimWeeb** [comment]
NOCOM-BOT/cli#1
